name: Build and Publish Maven Site

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  build-and-site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build project
        run: mvn -B clean install

      - name: Run quality plugins and generate site
        run: mvn -B verify site -ntp

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-site
          path: target/site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site

